/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicaion_auxiliar;

//import javafx.scene.paint.Color;
import aplicacion.*;
import javax.swing.JPanel;

/**
 *
 * @author barcelona
 */
public class Modulos_aux extends javax.swing.JFrame {

    /**
     * Creates new form Modulos
     */
       public static String user_nombres_aux = "";
    public static String user_apellidos_aux = "";
    public Modulos_aux() {
        initComponents();
        this.setLocationRelativeTo(null);
         user_nombres_aux=Login.usuario_nombres;
         user_apellidos_aux=Login.usuario_apellidos;
         jLauxiliar.setText(user_nombres_aux+" "+user_apellidos_aux);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2_aux = new javax.swing.JPanel();
        jPanel3_aux = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLauxiliar = new javax.swing.JLabel();
        jPanel_ingresos_aux = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel_home_aux = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel_cruces_aux = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel_analisis_aux = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel_aplicacion_aux = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel2_aux.setBackground(new java.awt.Color(233, 235, 238));
        jPanel2_aux.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3_aux.setBackground(new java.awt.Color(41, 128, 185));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Logout_Rounded_Left_40px.png"))); // NOI18N
        jLabel13.setText("Logout");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(86, 86, 86));
        jLabel15.setText("Bienvenido Auxiliar:");

        jLauxiliar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLauxiliar.setForeground(new java.awt.Color(86, 86, 86));
        jLauxiliar.setText("jLabel16");

        javax.swing.GroupLayout jPanel3_auxLayout = new javax.swing.GroupLayout(jPanel3_aux);
        jPanel3_aux.setLayout(jPanel3_auxLayout);
        jPanel3_auxLayout.setHorizontalGroup(
            jPanel3_auxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3_auxLayout.createSequentialGroup()
                .addContainerGap(431, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLauxiliar)
                .addGap(98, 98, 98)
                .addComponent(jLabel13)
                .addContainerGap())
        );
        jPanel3_auxLayout.setVerticalGroup(
            jPanel3_auxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3_auxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addComponent(jLauxiliar))
        );

        jPanel2_aux.add(jPanel3_aux, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 100));

        jPanel_ingresos_aux.setBackground(new java.awt.Color(224, 226, 229));
        jPanel_ingresos_aux.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_ingresos_auxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_ingresos_auxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_ingresos_auxMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Edit_Property_55px.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setText("Ingresos");

        javax.swing.GroupLayout jPanel_ingresos_auxLayout = new javax.swing.GroupLayout(jPanel_ingresos_aux);
        jPanel_ingresos_aux.setLayout(jPanel_ingresos_auxLayout);
        jPanel_ingresos_auxLayout.setHorizontalGroup(
            jPanel_ingresos_auxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ingresos_auxLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel_ingresos_auxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27))
        );
        jPanel_ingresos_auxLayout.setVerticalGroup(
            jPanel_ingresos_auxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ingresos_auxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(45, 45, 45))
        );

        jPanel2_aux.add(jPanel_ingresos_aux, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 130, 120));

        jPanel_home_aux.setBackground(new java.awt.Color(224, 226, 229));
        jPanel_home_aux.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_home_auxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_home_auxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_home_auxMouseExited(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Home_55px.png"))); // NOI18N
        jLabel5.setText("home");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 255));
        jLabel6.setText("Home");

        javax.swing.GroupLayout jPanel_home_auxLayout = new javax.swing.GroupLayout(jPanel_home_aux);
        jPanel_home_aux.setLayout(jPanel_home_auxLayout);
        jPanel_home_auxLayout.setHorizontalGroup(
            jPanel_home_auxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_home_auxLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel_home_auxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel_home_auxLayout.setVerticalGroup(
            jPanel_home_auxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_home_auxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel2_aux.add(jPanel_home_aux, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 130, 120));

        jPanel_cruces_aux.setBackground(new java.awt.Color(224, 226, 229));
        jPanel_cruces_aux.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_cruces_auxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_cruces_auxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_cruces_auxMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Data_Transfer_55px.png"))); // NOI18N
        jLabel3.setText("home");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 255));
        jLabel4.setText("Cruces");

        javax.swing.GroupLayout jPanel_cruces_auxLayout = new javax.swing.GroupLayout(jPanel_cruces_aux);
        jPanel_cruces_aux.setLayout(jPanel_cruces_auxLayout);
        jPanel_cruces_auxLayout.setHorizontalGroup(
            jPanel_cruces_auxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_cruces_auxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_cruces_auxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        jPanel_cruces_auxLayout.setVerticalGroup(
            jPanel_cruces_auxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_cruces_auxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(45, 45, 45))
        );

        jPanel2_aux.add(jPanel_cruces_aux, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 130, 120));

        jPanel_analisis_aux.setBackground(new java.awt.Color(224, 226, 229));
        jPanel_analisis_aux.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_analisis_auxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_analisis_auxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_analisis_auxMouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Search_55px_1.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 255));
        jLabel8.setText("Analisis");

        javax.swing.GroupLayout jPanel_analisis_auxLayout = new javax.swing.GroupLayout(jPanel_analisis_aux);
        jPanel_analisis_aux.setLayout(jPanel_analisis_auxLayout);
        jPanel_analisis_auxLayout.setHorizontalGroup(
            jPanel_analisis_auxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_analisis_auxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_analisis_auxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(31, 31, 31))
        );
        jPanel_analisis_auxLayout.setVerticalGroup(
            jPanel_analisis_auxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_analisis_auxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(45, 45, 45))
        );

        jPanel2_aux.add(jPanel_analisis_aux, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 130, 120));

        jPanel_aplicacion_aux.setBackground(new java.awt.Color(224, 226, 229));
        jPanel_aplicacion_aux.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_aplicacion_auxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_aplicacion_auxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_aplicacion_auxMouseExited(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Checklist_55px_1.png"))); // NOI18N
        jLabel9.setText("home");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 255));
        jLabel10.setText(" Aplicaciòn");

        javax.swing.GroupLayout jPanel_aplicacion_auxLayout = new javax.swing.GroupLayout(jPanel_aplicacion_aux);
        jPanel_aplicacion_aux.setLayout(jPanel_aplicacion_auxLayout);
        jPanel_aplicacion_auxLayout.setHorizontalGroup(
            jPanel_aplicacion_auxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_aplicacion_auxLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel_aplicacion_auxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_aplicacion_auxLayout.setVerticalGroup(
            jPanel_aplicacion_auxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_aplicacion_auxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel2_aux.add(jPanel_aplicacion_aux, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 130, 120));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(146, 146, 146));
        jLabel11.setText("Desarrolladores: Acosta Alvarado Nexar Jesús - Carrillo Moran Fatima Guadalupe ");
        jPanel2_aux.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(146, 146, 146));
        jLabel14.setText(" Propiedad Intelectual Facultad de Ciencias Informaticas - ULEAM");
        jPanel2_aux.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(146, 146, 146));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Copyright_15px.png"))); // NOI18N
        jLabel12.setText("Copyright 2017 - 2018");
        jPanel2_aux.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 560, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2_aux, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2_aux, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel_home_auxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_home_auxMouseEntered
        // TODO add your handling code here:
        setColor(jPanel_home_aux);
    }//GEN-LAST:event_jPanel_home_auxMouseEntered

    private void jPanel_home_auxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_home_auxMouseExited
        // TODO add your handling code here:
        resetColor(jPanel_home_aux);
    }//GEN-LAST:event_jPanel_home_auxMouseExited

    private void jPanel_ingresos_auxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_ingresos_auxMouseEntered
        // TODO add your handling code here:
        setColor(jPanel_ingresos_aux);
    }//GEN-LAST:event_jPanel_ingresos_auxMouseEntered

    private void jPanel_ingresos_auxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_ingresos_auxMouseExited
        // TODO add your handling code here:
        resetColor(jPanel_ingresos_aux);
    }//GEN-LAST:event_jPanel_ingresos_auxMouseExited

    private void jPanel_cruces_auxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_cruces_auxMouseEntered
        // TODO add your handling code here:
        setColor(jPanel_cruces_aux);
    }//GEN-LAST:event_jPanel_cruces_auxMouseEntered

    private void jPanel_cruces_auxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_cruces_auxMouseExited
        // TODO add your handling code here:
        resetColor(jPanel_cruces_aux);
    }//GEN-LAST:event_jPanel_cruces_auxMouseExited

    private void jPanel_analisis_auxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_analisis_auxMouseEntered
        // TODO add your handling code here:
        setColor(jPanel_analisis_aux);
    }//GEN-LAST:event_jPanel_analisis_auxMouseEntered

    private void jPanel_analisis_auxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_analisis_auxMouseExited
        // TODO add your handling code here:
        resetColor(jPanel_analisis_aux);
    }//GEN-LAST:event_jPanel_analisis_auxMouseExited

    private void jPanel_aplicacion_auxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_aplicacion_auxMouseEntered
        // TODO add your handling code here:
        setColor(jPanel_aplicacion_aux);
    }//GEN-LAST:event_jPanel_aplicacion_auxMouseEntered

    private void jPanel_aplicacion_auxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_aplicacion_auxMouseExited
        // TODO add your handling code here:
        resetColor(jPanel_aplicacion_aux);
    }//GEN-LAST:event_jPanel_aplicacion_auxMouseExited

    private void jPanel_home_auxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_home_auxMouseClicked
        // TODO add your handling code here:
       
        Auxiliar aux = new Auxiliar();
        aux.setVisible(true);
        this.setVisible(false);
       


    }//GEN-LAST:event_jPanel_home_auxMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
//        Analisis anali = new Analisis();
//        anali.setVisible(true);
//        this.setVisible(false);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
//        Cruce1 rs = new Cruce1();
//        rs.setVisible(true);
//        this.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jPanel_ingresos_auxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_ingresos_auxMouseClicked
        // TODO add your handling code here:
      this.setVisible(false);
      Ingresos_aux ing_aux = new Ingresos_aux();
      ing_aux.setVisible(true);
    }//GEN-LAST:event_jPanel_ingresos_auxMouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        this.setVisible(false);
        Login visi = new Login();
        visi.setVisible(true);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jPanel_cruces_auxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_cruces_auxMouseClicked
       this.setVisible(false);
       cruces_activos_amenazas_aux cruces_aux = new cruces_activos_amenazas_aux();
       cruces_aux.setVisible(true);
    }//GEN-LAST:event_jPanel_cruces_auxMouseClicked

    private void jPanel_analisis_auxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_analisis_auxMouseClicked
        this.setVisible(false);
        Analisis_aux analisis_aux = new Analisis_aux();
        analisis_aux.setVisible(true);

    }//GEN-LAST:event_jPanel_analisis_auxMouseClicked

    private void jPanel_aplicacion_auxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_aplicacion_auxMouseClicked
       this.setVisible(false);
        AplicacionIsos_aux aplicacion_aux = new AplicacionIsos_aux();
        aplicacion_aux.setVisible(true);
    }//GEN-LAST:event_jPanel_aplicacion_auxMouseClicked
    public void setColor(JPanel jpanel) {

        jpanel.setBackground(new java.awt.Color(204, 203, 203));

    }

    public void resetColor(JPanel jpanel) {

        jpanel.setBackground(new java.awt.Color(224, 226, 229));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modulos_aux.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modulos_aux.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modulos_aux.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modulos_aux.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modulos_aux().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLauxiliar;
    public static javax.swing.JPanel jPanel2_aux;
    private javax.swing.JPanel jPanel3_aux;
    private javax.swing.JPanel jPanel_analisis_aux;
    private javax.swing.JPanel jPanel_aplicacion_aux;
    private javax.swing.JPanel jPanel_cruces_aux;
    private javax.swing.JPanel jPanel_home_aux;
    private javax.swing.JPanel jPanel_ingresos_aux;
    // End of variables declaration//GEN-END:variables
}
