/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacion;

import javax.swing.JPanel;

/**
 *
 * @author barcelona
 */
public class Administrador extends javax.swing.JFrame {

    /** 
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel_contacto = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel_informacion = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel_registrouser = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        labelconectado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel_principal = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_institucion = new javax.swing.JLabel();
        jLabel_nombres1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel_apellidos = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel_sexo = new javax.swing.JLabel();
        jLabel_edad = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel_correo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_celular = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel13 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(27, 29, 37));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_contacto.setBackground(new java.awt.Color(27, 29, 37));
        jPanel_contacto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_contactoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_contactoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_contactoMouseExited(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Contacto");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Phone_20px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_contactoLayout = new javax.swing.GroupLayout(jPanel_contacto);
        jPanel_contacto.setLayout(jPanel_contactoLayout);
        jPanel_contactoLayout.setHorizontalGroup(
            jPanel_contactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_contactoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel11)
                .addGap(20, 20, 20)
                .addComponent(jLabel9))
        );
        jPanel_contactoLayout.setVerticalGroup(
            jPanel_contactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.add(jPanel_contacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 210, 50));

        jPanel_informacion.setBackground(new java.awt.Color(27, 29, 37));
        jPanel_informacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_informacionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_informacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_informacionMouseExited(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Informacion");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_More_Info_20px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_informacionLayout = new javax.swing.GroupLayout(jPanel_informacion);
        jPanel_informacion.setLayout(jPanel_informacionLayout);
        jPanel_informacionLayout.setHorizontalGroup(
            jPanel_informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_informacionLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel19)
                .addGap(20, 20, 20)
                .addComponent(jLabel18))
        );
        jPanel_informacionLayout.setVerticalGroup(
            jPanel_informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.add(jPanel_informacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 210, 50));

        jPanel_registrouser.setBackground(new java.awt.Color(27, 29, 37));
        jPanel_registrouser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_registrouserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_registrouserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_registrouserMouseExited(evt);
            }
        });

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Registro Usuario");

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Add_User_Male_20px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_registrouserLayout = new javax.swing.GroupLayout(jPanel_registrouser);
        jPanel_registrouser.setLayout(jPanel_registrouserLayout);
        jPanel_registrouserLayout.setHorizontalGroup(
            jPanel_registrouserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_registrouserLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel21)
                .addGap(20, 20, 20)
                .addComponent(jLabel20))
        );
        jPanel_registrouserLayout.setVerticalGroup(
            jPanel_registrouserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.add(jPanel_registrouser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 190, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 510));

        jPanel3.setBackground(new java.awt.Color(117, 117, 123));

        labelconectado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelconectado.setText("bienvenido");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Administrador");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelconectado)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(368, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelconectado)
                    .addComponent(jLabel1))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 550, -1));

        jPanel_principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setText("Instituciòn:");
        jPanel_principal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel_institucion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_institucion.setText("jLabel10");
        jPanel_principal.add(jLabel_institucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        jLabel_nombres1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_nombres1.setText("jLabel10");
        jPanel_principal.add(jLabel_nombres1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Nombres:");
        jPanel_principal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Name_40px.png"))); // NOI18N
        jPanel_principal.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Apellidos:");
        jPanel_principal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        jLabel_apellidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_apellidos.setText("jLabel10");
        jPanel_principal.add(jLabel_apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));
        jPanel_principal.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 270, 10));

        jLabel_sexo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_sexo.setText("jLabel10");
        jPanel_principal.add(jLabel_sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        jLabel_edad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_edad.setText("jLabel10");
        jPanel_principal.add(jLabel_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Edad:");
        jPanel_principal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Sexo:");
        jPanel_principal.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Info_40px.png"))); // NOI18N
        jPanel_principal.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));
        jPanel_principal.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 270, 10));

        jLabel_correo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_correo.setText("jLabel10");
        jPanel_principal.add(jLabel_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Correo:");
        jPanel_principal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Contact_40px.png"))); // NOI18N
        jPanel_principal.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Celular:");
        jPanel_principal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        jLabel_celular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_celular.setText("jLabel10");
        jPanel_principal.add(jLabel_celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        jPanel1.add(jPanel_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 550, 370));

        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 210, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 210, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, 270, 10));

        jPanel13.setBackground(new java.awt.Color(55, 58, 70));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Informacion");
        jPanel13.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 50));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_More_Info_20px.png"))); // NOI18N
        jPanel13.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 190, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jPanel_informacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_informacionMouseEntered
        // TODO add your handling code here:
         setColor(jPanel_informacion);
          
    }//GEN-LAST:event_jPanel_informacionMouseEntered

    private void jPanel_informacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_informacionMouseExited
        // TODO add your handling code here:
        resetColor(jPanel_informacion);
    }//GEN-LAST:event_jPanel_informacionMouseExited

    private void jPanel_registrouserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_registrouserMouseEntered
        // TODO add your handling code here:
        setColor(jPanel_registrouser);
    }//GEN-LAST:event_jPanel_registrouserMouseEntered

    private void jPanel_registrouserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_registrouserMouseExited
        // TODO add your handling code here:
         resetColor(jPanel_registrouser);
    }//GEN-LAST:event_jPanel_registrouserMouseExited

    private void jPanel_contactoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_contactoMouseEntered
        // TODO add your handling code here:
        setColor(jPanel_contacto);
    }//GEN-LAST:event_jPanel_contactoMouseEntered

    private void jPanel_contactoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_contactoMouseExited
        // TODO add your handling code here:
        resetColor(jPanel_contacto);
    }//GEN-LAST:event_jPanel_contactoMouseExited

    private void jPanel_informacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_informacionMouseClicked
        // TODO add your handling code here:
        Administrador administrador=new Administrador();
        administrador.setVisible(true);
        dispose();
       
    }//GEN-LAST:event_jPanel_informacionMouseClicked

    private void jPanel_registrouserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_registrouserMouseClicked
        // TODO add your handling code here:
       RegistroUsuario registro= new RegistroUsuario();
        registro.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jPanel_registrouserMouseClicked

    private void jPanel_contactoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_contactoMouseClicked
        // TODO add your handling code here:
        Contacto contacto = new Contacto();
        contacto.setVisible(true);
        dispose();
         Contacto cont= new Contacto();
       //  jPanel1.add(cont);
        // cont.show();
    }//GEN-LAST:event_jPanel_contactoMouseClicked
 public void setColor(JPanel jpanel){
        
        jpanel.setBackground(new java.awt.Color(60,64,77));
        
    }
    public void resetColor(JPanel jpanel){
        
        jpanel.setBackground(new java.awt.Color(27,29,37));
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_apellidos;
    private javax.swing.JLabel jLabel_celular;
    private javax.swing.JLabel jLabel_correo;
    private javax.swing.JLabel jLabel_edad;
    private javax.swing.JLabel jLabel_institucion;
    private javax.swing.JLabel jLabel_nombres1;
    private javax.swing.JLabel jLabel_sexo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_contacto;
    private javax.swing.JPanel jPanel_informacion;
    public static javax.swing.JPanel jPanel_principal;
    private javax.swing.JPanel jPanel_registrouser;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTextField1;
    public static javax.swing.JLabel labelconectado;
    // End of variables declaration//GEN-END:variables
}
