/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacion;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import jdk.nashorn.internal.scripts.JO;
import metodos.Conexionbd;

/**
 *
 * @author Leonardo
 */
public class Amenazas extends javax.swing.JFrame {

    /**
     * Creates new form Ingresos
     */
    public Amenazas() throws SQLException {
        initComponents();
        AM1();
        AM2();
        AM3();
        AM4();
        AM5();
        AM6();
 this.setLocationRelativeTo(null);
    }

    void Limpiar() {
        Textamenaza.setText("");
        tipo_amenaza.setSelectedIndex(0);

    }

    private void AM1() throws SQLException {
        DefaultListModel<String> modelo = new DefaultListModel<>();
        String sql = "";
        sql = "select nombre_amenaza from amenaza where tipo_amenaza='AM1'";
        Statement st = cxn.createStatement();
        ResultSet rs = st.executeQuery(sql);
        while (rs.next()) {
            modelo.addElement(rs.getString("nombre_amenaza"));
            jList_a1.setModel(modelo);
        }
    }

    private void AM2() throws SQLException {
        DefaultListModel<String> modelo = new DefaultListModel<>();
        String sql = "";
        sql = "select nombre_amenaza from amenaza where tipo_amenaza='AM2'";
        Statement st = cxn.createStatement();
        ResultSet rs = st.executeQuery(sql);
        while (rs.next()) {
            modelo.addElement(rs.getString("nombre_amenaza"));
            jList_a2.setModel(modelo);
        }
    }

    private void AM3() throws SQLException {
        DefaultListModel<String> modelo = new DefaultListModel<>();
        String sql = "";
        sql = "select nombre_amenaza from amenaza where tipo_amenaza='AM3'";
        Statement st = cxn.createStatement();
        ResultSet rs = st.executeQuery(sql);
        while (rs.next()) {
            modelo.addElement(rs.getString("nombre_amenaza"));
            jList_a3.setModel(modelo);
        }
    }

    private void AM4() throws SQLException {
        DefaultListModel<String> modelo = new DefaultListModel<>();
        String sql = "";
        sql = "select nombre_amenaza from amenaza where tipo_amenaza='AM4'";
        Statement st = cxn.createStatement();
        ResultSet rs = st.executeQuery(sql);
        while (rs.next()) {
            modelo.addElement(rs.getString("nombre_amenaza"));
            jList_a4.setModel(modelo);
        }
    }

    private void AM5() throws SQLException {
        DefaultListModel<String> modelo = new DefaultListModel<>();
        String sql = "";
        sql = "select nombre_amenaza from amenaza where tipo_amenaza='AM5'";
        Statement st = cxn.createStatement();
        ResultSet rs = st.executeQuery(sql);
        while (rs.next()) {
            modelo.addElement(rs.getString("nombre_amenaza"));
            jList_a5.setModel(modelo);
        }
    }

    private void AM6() throws SQLException {
        DefaultListModel<String> modelo = new DefaultListModel<>();
        String sql = "";
        sql = "select nombre_amenaza from amenaza where tipo_amenaza='AM6'";
        Statement st = cxn.createStatement();
        ResultSet rs = st.executeQuery(sql);
        while (rs.next()) {
            modelo.addElement(rs.getString("nombre_amenaza"));
            jList_a6.setModel(modelo);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_amenazas = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jList_a1 = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        jList_a2 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList_a3 = new javax.swing.JList<>();
        jScrollPane10 = new javax.swing.JScrollPane();
        jList_a4 = new javax.swing.JList<>();
        jScrollPane11 = new javax.swing.JScrollPane();
        jList_a5 = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        jList_a6 = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tipo_amenaza = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        Textamenaza = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton_eliminar = new javax.swing.JButton();
        jButton_modificar = new javax.swing.JButton();
        jButton_guardar = new javax.swing.JButton();
        jButton_nuevo = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Bamenaza = new javax.swing.JButton();
        Bactivo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_amenazas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 4), "Amenazas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 13))); // NOI18N

        jList_a1.setBackground(new java.awt.Color(240, 240, 240));
        jList_a1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jList_a1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList_a1MouseClicked(evt);
            }
        });
        jList_a1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_a1ValueChanged(evt);
            }
        });
        jScrollPane9.setViewportView(jList_a1);

        jList_a2.setBackground(new java.awt.Color(240, 240, 240));
        jList_a2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jList_a2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "AMENAZAS", "" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList_a2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_a2ValueChanged(evt);
            }
        });
        jScrollPane7.setViewportView(jList_a2);

        jList_a3.setBackground(new java.awt.Color(240, 240, 240));
        jList_a3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jList_a3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jList_a3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "AMENAZAS", "" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList_a3.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_a3ValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(jList_a3);

        jList_a4.setBackground(new java.awt.Color(240, 240, 240));
        jList_a4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jList_a4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "AMENAZAS", "" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList_a4.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_a4ValueChanged(evt);
            }
        });
        jScrollPane10.setViewportView(jList_a4);

        jList_a5.setBackground(new java.awt.Color(240, 240, 240));
        jList_a5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jList_a5.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "AMENAZAS" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList_a5.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_a5ValueChanged(evt);
            }
        });
        jScrollPane11.setViewportView(jList_a5);

        jList_a6.setBackground(new java.awt.Color(240, 240, 240));
        jList_a6.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jList_a6.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "AMENAZAS", "" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList_a6.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_a6ValueChanged(evt);
            }
        });
        jScrollPane8.setViewportView(jList_a6);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setText("A2");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setText("A3");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setText("A1");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setText("A4");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setText("A5");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setText(" A6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel8)
                        .addGap(276, 276, 276)
                        .addComponent(jLabel9)
                        .addGap(266, 266, 266)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel5)
                        .addGap(276, 276, 276)
                        .addComponent(jLabel6)
                        .addGap(266, 266, 266)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel1))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel_amenazas.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 870, 340));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3), "Registrar Amenaza", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 13))); // NOI18N

        tipo_amenaza.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tipo_amenaza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM1", "AM2", "AM3", "AM4", "AM5", "AM6" }));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel4.setText("Tipo Amenaza:");

        Textamenaza.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Textamenaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextamenazaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel3.setText("Amenaza:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(Textamenaza, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(4, 4, 4)
                .addComponent(tipo_amenaza, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(Textamenaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(tipo_amenaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jPanel_amenazas.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 550, 60));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_eliminar.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Delete_Row_30px_1.png"))); // NOI18N
        jButton_eliminar.setText("Eliminar");
        jButton_eliminar.setBorder(null);
        jButton_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eliminarActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 100, 40));

        jButton_modificar.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Edit_Property_30px.png"))); // NOI18N
        jButton_modificar.setText("Modificar");
        jButton_modificar.setBorder(null);
        jButton_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_modificarActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 100, 40));

        jButton_guardar.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Save_30px.png"))); // NOI18N
        jButton_guardar.setText("Guardar");
        jButton_guardar.setBorder(null);
        jButton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardarActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 100, 40));

        jButton_nuevo.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Available_Updates_30px_2.png"))); // NOI18N
        jButton_nuevo.setText("Nuevo");
        jButton_nuevo.setBorder(null);
        jButton_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nuevoActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 100, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Go_Back_40px.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel_amenazas.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 60));

        getContentPane().add(jPanel_amenazas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 900, 520));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bamenaza.setBackground(new java.awt.Color(47, 54, 64));
        Bamenaza.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Bamenaza.setForeground(new java.awt.Color(255, 255, 255));
        Bamenaza.setText("Amenaza");
        Bamenaza.setBorder(null);
        Bamenaza.setContentAreaFilled(false);
        Bamenaza.setOpaque(true);
        Bamenaza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BamenazaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BamenazaMouseExited(evt);
            }
        });
        Bamenaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BamenazaActionPerformed(evt);
            }
        });
        jPanel2.add(Bamenaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 430, 50));

        Bactivo.setBackground(new java.awt.Color(47, 54, 64));
        Bactivo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Bactivo.setForeground(new java.awt.Color(255, 255, 255));
        Bactivo.setText("Activo");
        Bactivo.setBorder(null);
        Bactivo.setContentAreaFilled(false);
        Bactivo.setOpaque(true);
        Bactivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BactivoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BactivoMouseExited(evt);
            }
        });
        Bactivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BactivoActionPerformed(evt);
            }
        });
        jPanel2.add(Bactivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int id_amenaza1() {
        String fila = jList_a1.getSelectedValue();
        int id_amenaza = 0;
        String sql1 = "select idamenaza, nombre_amenaza  from amenaza where nombre_amenaza='" + fila + "'";
        try {
            Statement st = cxn.createStatement();
            ResultSet rs = st.executeQuery(sql1);
            while (rs.next()) {
                id_amenaza = rs.getInt("idamenaza");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return id_amenaza;
    }

    int id_amenaza2() {
        String fila = jList_a2.getSelectedValue();
        int id_amenaza = 0;
        String sql1 = "select idamenaza, nombre_amenaza  from amenaza where nombre_amenaza='" + fila + "'";
        try {
            Statement st = cxn.createStatement();
            ResultSet rs = st.executeQuery(sql1);
            while (rs.next()) {
                id_amenaza = rs.getInt("idamenaza");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return id_amenaza;
    }

    int id_amenaza3() {
        String fila = jList_a3.getSelectedValue();
        int id_amenaza = 0;
        String sql1 = "select idamenaza, nombre_amenaza  from amenaza where nombre_amenaza='" + fila + "'";
        try {
            Statement st = cxn.createStatement();
            ResultSet rs = st.executeQuery(sql1);
            while (rs.next()) {
                id_amenaza = rs.getInt("idamenaza");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return id_amenaza;
    }

    int id_amenaza4() {
        String fila = jList_a4.getSelectedValue();
        int id_amenaza = 0;
        String sql1 = "select idamenaza, nombre_amenaza  from amenaza where nombre_amenaza='" + fila + "'";
        try {
            Statement st = cxn.createStatement();
            ResultSet rs = st.executeQuery(sql1);
            while (rs.next()) {
                id_amenaza = rs.getInt("idamenaza");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return id_amenaza;
    }

    int id_amenaza5() {
        String fila = jList_a5.getSelectedValue();
        int id_amenaza = 0;
        String sql1 = "select idamenaza, nombre_amenaza  from amenaza where nombre_amenaza='" + fila + "'";
        try {
            Statement st = cxn.createStatement();
            ResultSet rs = st.executeQuery(sql1);
            while (rs.next()) {
                id_amenaza = rs.getInt("idamenaza");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return id_amenaza;
    }

    int id_amenaza6() {
        String fila = jList_a6.getSelectedValue();
        int id_amenaza = 0;
        String sql1 = "select idamenaza, nombre_amenaza  from amenaza where nombre_amenaza='" + fila + "'";
        try {
            Statement st = cxn.createStatement();
            ResultSet rs = st.executeQuery(sql1);
            while (rs.next()) {
                id_amenaza = rs.getInt("idamenaza");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return id_amenaza;
    }

    void eliminar1() {
        String sql = "delete from amenaza where idamenaza='" + id_amenaza1() + "'";
        try {
            Statement st = cxn.createStatement();
            int n = st.executeUpdate(sql);
            if (n > 0) {
                JOptionPane.showMessageDialog(null, "datos eliminados");
                AM1();
                Limpiar();
            }
        } catch (Exception e) {
        }

    }

    void eliminar2() {
        String sql = "delete from amenaza where idamenaza='" + id_amenaza2() + "'";
        try {
            Statement st = cxn.createStatement();
            int n = st.executeUpdate(sql);
            if (n > 0) {
                JOptionPane.showMessageDialog(null, "datos eliminados");
                AM2();
                Limpiar();
            }
        } catch (Exception e) {
        }
    }

    void eliminar3() {
        String sql = "delete from amenaza where idamenaza='" + id_amenaza3() + "'";
        try {
            Statement st = cxn.createStatement();
            int n = st.executeUpdate(sql);
            if (n > 0) {
                JOptionPane.showMessageDialog(null, "datos eliminados");
                AM3();
                Limpiar();
            }
        } catch (Exception e) {
        }
    }

    void eliminar4() {
        String sql = "delete from amenaza where idamenaza='" + id_amenaza4() + "'";
        try {
            Statement st = cxn.createStatement();
            int n = st.executeUpdate(sql);
            if (n > 0) {
                JOptionPane.showMessageDialog(null, "datos eliminados");
                AM4();
                Limpiar();
            }
        } catch (Exception e) {
        }
    }

    void eliminar5() {
        String sql = "delete from amenaza where idamenaza='" + id_amenaza5() + "'";
        try {
            Statement st = cxn.createStatement();
            int n = st.executeUpdate(sql);
            if (n > 0) {
                JOptionPane.showMessageDialog(null, "datos eliminados");
                AM5();
                Limpiar();
            }
        } catch (Exception e) {
        }
    }

    void eliminar6() {
        String sql = "delete from amenaza where idamenaza='" + id_amenaza6() + "'";
        try {
            Statement st = cxn.createStatement();
            int n = st.executeUpdate(sql);
            if (n > 0) {
                JOptionPane.showMessageDialog(null, "datos eliminados");
                AM6();
                Limpiar();
            }
        } catch (Exception e) {
        }
    }
    private void jButton_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nuevoActionPerformed
        Limpiar();
    }//GEN-LAST:event_jButton_nuevoActionPerformed
    void modificar1() {
        String nombre_amen = Textamenaza.getText();
        String sql = "update amenaza set nombre_amenaza='" + nombre_amen + "' where idamenaza='" + id_amenaza1() + "'";
        try {
            PreparedStatement ps = cxn.prepareCall(sql);
            int n = ps.executeUpdate();
            if (n > 0) {
                JOptionPane.showMessageDialog(null, "datos modificado");
                Limpiar();
                AM1();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "error" + e.getMessage());
        }
    }

    void modificar2() {
        String nombre_amen = Textamenaza.getText();
        String sql = "update amenaza set nombre_amenaza='" + nombre_amen + "' where idamenaza='" + id_amenaza2() + "'";
        try {
            PreparedStatement ps = cxn.prepareCall(sql);
            int n = ps.executeUpdate();
            if (n > 0) {

                JOptionPane.showMessageDialog(null, "datos modificado");
                Limpiar();
                AM2();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "error" + e.getMessage());
        }
    }

    void modificar3() {
        String nombre_amen = Textamenaza.getText();
        String sql = "update amenaza set nombre_amenaza='" + nombre_amen + "' where idamenaza='" + id_amenaza3() + "'";
        try {
            PreparedStatement ps = cxn.prepareCall(sql);
             int n = ps.executeUpdate();
            if (n > 0) {

                JOptionPane.showMessageDialog(null, "datos modificado");
                Limpiar();
                AM3();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "error" + e.getMessage());
        }
    }

    void modificar4() {
        String nombre_amen = Textamenaza.getText();
        String sql = "update amenaza set nombre_amenaza='" + nombre_amen + "' where idamenaza='" + id_amenaza4() + "'";
        try {
            PreparedStatement ps = cxn.prepareCall(sql);
             int n = ps.executeUpdate();
            if (n > 0) {

                JOptionPane.showMessageDialog(null, "datos modificado");
                Limpiar();
                AM4();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "error" + e.getMessage());
        }
    }

    void modificar5() {
        String nombre_amen = Textamenaza.getText();
        String sql = "update amenaza set nombre_amenaza='" + nombre_amen + "' where idamenaza='" + id_amenaza5() + "'";
        try {
            PreparedStatement ps = cxn.prepareCall(sql);
              int n = ps.executeUpdate();
            if (n > 0) {

                JOptionPane.showMessageDialog(null, "datos modificado");
                Limpiar();
                AM5();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "error" + e.getMessage());
        }
    }

    void modificar6() {
        String nombre_amen = Textamenaza.getText();
        String sql = "update amenaza set nombre_amenaza='" + nombre_amen + "' where idamenaza='" + id_amenaza6() + "'";
        try {
            PreparedStatement ps = cxn.prepareCall(sql);
            int n = ps.executeUpdate();
            if (n > 0) {

                JOptionPane.showMessageDialog(null, "datos modificado");
                Limpiar();
                AM6();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "error" + e.getMessage());
        }
    }
    private void jButton_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_modificarActionPerformed
        modificar1();
        modificar2();
        modificar3();
        modificar4();
        modificar5();
        modificar6();
    }//GEN-LAST:event_jButton_modificarActionPerformed

    private void jButton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_guardarActionPerformed
        String sql = "";
        sql = "insert into amenaza(nombre_amenaza, tipo_amenaza) values(?,?)";

        try {
            PreparedStatement dato = cxn.prepareStatement(sql);
            dato.setString(1, Textamenaza.getText().toString());
            dato.setString(2, tipo_amenaza.getModel().getSelectedItem().toString());
            dato.executeUpdate();
            AM1();
            AM2();
            AM3();
            AM4();
            AM5();
            AM6();
            Limpiar();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_jButton_guardarActionPerformed

    private void TextamenazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextamenazaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextamenazaActionPerformed

    private void jList_a1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_a1ValueChanged

        String valor2 = jList_a1.getSelectedValue();
        String sql = "select nombre_amenaza, tipo_amenaza from amenaza where "
                + "nombre_amenaza= '" + valor2 + "'";
        try {
            Statement st = cxn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                String amenaza = rs.getString("nombre_amenaza");
                String tipo = rs.getString("tipo_amenaza");
                Textamenaza.setText(amenaza);
                tipo_amenaza.getModel().setSelectedItem(tipo);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_jList_a1ValueChanged

    private void jList_a2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_a2ValueChanged
        String valor2 = jList_a2.getSelectedValue();
        String sql = "select nombre_amenaza, tipo_amenaza from amenaza where "
                + "nombre_amenaza= '" + valor2 + "'";
        try {
            Statement st = cxn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                String amenaza = rs.getString("nombre_amenaza");
                String tipo = rs.getString("tipo_amenaza");
                Textamenaza.setText(amenaza);
                tipo_amenaza.getModel().setSelectedItem(tipo);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jList_a2ValueChanged

    private void jList_a1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList_a1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jList_a1MouseClicked

    private void jList_a3ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_a3ValueChanged
        String valor2 = jList_a3.getSelectedValue();
        String sql = "select nombre_amenaza, tipo_amenaza from amenaza where "
                + "nombre_amenaza= '" + valor2 + "'";
        try {
            Statement st = cxn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                String amenaza = rs.getString("nombre_amenaza");
                String tipo = rs.getString("tipo_amenaza");
                Textamenaza.setText(amenaza);
                tipo_amenaza.getModel().setSelectedItem(tipo);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jList_a3ValueChanged

    private void jList_a4ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_a4ValueChanged
        String valor2 = jList_a4.getSelectedValue();
        String sql = "select nombre_amenaza, tipo_amenaza from amenaza where "
                + "nombre_amenaza= '" + valor2 + "'";
        try {
            Statement st = cxn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                String amenaza = rs.getString("nombre_amenaza");
                String tipo = rs.getString("tipo_amenaza");
                Textamenaza.setText(amenaza);
                tipo_amenaza.getModel().setSelectedItem(tipo);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jList_a4ValueChanged

    private void jList_a5ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_a5ValueChanged
        String valor2 = jList_a5.getSelectedValue();
        String sql = "select nombre_amenaza, tipo_amenaza from amenaza where "
                + "nombre_amenaza= '" + valor2 + "'";
        try {
            Statement st = cxn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                String amenaza = rs.getString("nombre_amenaza");
                String tipo = rs.getString("tipo_amenaza");
                Textamenaza.setText(amenaza);
                tipo_amenaza.getModel().setSelectedItem(tipo);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }    }//GEN-LAST:event_jList_a5ValueChanged

    private void jList_a6ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_a6ValueChanged
        String valor2 = jList_a6.getSelectedValue();
        String sql = "select nombre_amenaza, tipo_amenaza from amenaza where "
                + "nombre_amenaza= '" + valor2 + "'";
        try {
            Statement st = cxn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                String amenaza = rs.getString("nombre_amenaza");
                String tipo = rs.getString("tipo_amenaza");
                Textamenaza.setText(amenaza);
                tipo_amenaza.getModel().setSelectedItem(tipo);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }    }//GEN-LAST:event_jList_a6ValueChanged

    private void jButton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eliminarActionPerformed
        eliminar1();
        eliminar2();
        eliminar3();
        eliminar4();
        eliminar5();
        eliminar6();

    }//GEN-LAST:event_jButton_eliminarActionPerformed

    private void BamenazaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BamenazaMouseEntered
        setColor(Bamenaza);
    }//GEN-LAST:event_BamenazaMouseEntered

    private void BamenazaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BamenazaMouseExited
        resetColor(Bamenaza);
    }//GEN-LAST:event_BamenazaMouseExited

    private void BamenazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BamenazaActionPerformed

        //        ee e=new ee();
        //        jPanel_principal.add(e);
        //        e.setVisible(true);
        //e.show();
        //    rr.panel1.setVisible(true);
        //             this.jPanel_principal.add(un);
        //             un.setVisible(true);
        //        un.setSize(550, 510);
        //        un.setLocation(0, 0);
        //
        //       jPanel_principal.removeAll();
        //      jPanel_principal.removeAll();
        //
        //
        //
        //      jPanel_principal.add(un);
        //      un.setVisible(true);
        //      jPanel_principal.repaint();
        //      jPanel_principal.revalidate();
    }//GEN-LAST:event_BamenazaActionPerformed

    private void BactivoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BactivoMouseEntered
        setColor(Bactivo);
    }//GEN-LAST:event_BactivoMouseEntered

    private void BactivoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BactivoMouseExited
        resetColor(Bactivo);
    }//GEN-LAST:event_BactivoMouseExited
    public void setColor(JButton jbutton) {

        jbutton.setBackground(new java.awt.Color(52, 73, 94));

    }

    public void resetColor(JButton jbutton) {

        jbutton.setBackground(new java.awt.Color(47, 54, 64));

    }
    private void BactivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BactivoActionPerformed
       
          Ingresos ingresos = new Ingresos();
            ingresos.setVisible(true);
                 this.setVisible(false);
    }//GEN-LAST:event_BactivoActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        this.setVisible(false);
        Modulos modu=new Modulos();
        modu.setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Amenazas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Amenazas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Amenazas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Amenazas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                try {
                    new Amenazas().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Amenazas.class.getName()).log(Level.SEVERE, null, ex);
                }

                    
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bactivo;
    private javax.swing.JButton Bamenaza;
    public static javax.swing.JTextField Textamenaza;
    public static javax.swing.JButton jButton_eliminar;
    public static javax.swing.JButton jButton_guardar;
    public static javax.swing.JButton jButton_modificar;
    public static javax.swing.JButton jButton_nuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList_a1;
    private javax.swing.JList<String> jList_a2;
    private javax.swing.JList<String> jList_a3;
    private javax.swing.JList<String> jList_a4;
    private javax.swing.JList<String> jList_a5;
    private javax.swing.JList<String> jList_a6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JPanel jPanel_amenazas;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JComboBox<String> tipo_amenaza;
    // End of variables declaration//GEN-END:variables
    Conexionbd conxlogin = new Conexionbd();
    Connection cxn = conxlogin.getConnection();
    public static int idd = 0;
    // private ArrayList<jList_a1> lista = new ArrayList<>();

}
