/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacion;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JApplet;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import metodos.Conexionbd;

/**
 *
 * @author fatte
 */
public class Analisis extends javax.swing.JFrame {

    DefaultTableModel modelo;

    /**
     * Creates new form Analisis
     */
    public Analisis() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
//   void llenartabla(){
//   String [] activos= {"Cantidad","nombre_activo"};
//   modelo=new  DefaultTableModel(null,activos);   
//   String datos []= new String[5];
//   String sql="SELECT Cantidad,nombre_activo FROM activo"; 
//        try {
//            Statement st = cxn.createStatement();
//            ResultSet rs = st.executeQuery(sql);
//            while(rs.next())
//            { 
//                datos[0]=rs.getString("Cantidad");
//                datos[1]=rs.getString("nombre_activo");
//                //datos[2]= rs.getString("usuario");
//                //datos[3]= rs.getString("tipo_usuario");
//                
//                modelo.addRow(datos);
//            }
//            jTable1.setModel(modelo);
//        } catch (SQLException ex) {
//            Logger.getLogger(RegistroUsuario.class.getName()).log(Level.SEVERE, null, ex);
//        }
//  
//  
//   } 
    Conexionbd conxlogin = new Conexionbd();
    Connection cxn = conxlogin.getConnection();
    String idfila = "";

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_analisis = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton_nuevo = new javax.swing.JButton();

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(900, 560));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(233, 235, 238));
        jPanel3.setMinimumSize(new java.awt.Dimension(900, 560));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 4), "Analisis de Riesgo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 13))); // NOI18N

        jTable_analisis.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTable_analisis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Activos", "Amenazas", "Probabilidad", "Impacto", "Riesgo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable_analisis);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 850, 470));

        jPanel5.setBackground(new java.awt.Color(113, 128, 147));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Set_As_Resume_30px.png"))); // NOI18N
        jButton8.setText("Reporte");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 120, -1));

        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Microsoft_Excel_30px.png"))); // NOI18N
        jButton7.setText("Exportar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 120, -1));

        jButton9.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Save_30px.png"))); // NOI18N
        jButton9.setText("Guardar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 120, -1));

        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Analyze_30px.png"))); // NOI18N
        jButton6.setText("Visualizar Análisis");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 170, 41));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Go_Back_40px.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton_nuevo.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Available_Updates_30px_2.png"))); // NOI18N
        jButton_nuevo.setText("Nuevo");
        jButton_nuevo.setBorder(null);
        jButton_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nuevoActionPerformed(evt);
            }
        });
        jPanel5.add(jButton_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 120, 40));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 60));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  public void setColor(JButton jbutton) {

        jbutton.setBackground(new java.awt.Color(52, 73, 94));

    }

    public void resetColor(JButton jbutton) {

        jbutton.setBackground(new java.awt.Color(47, 54, 64));

    }

    public void mostrar_combox() {

//        int colum = jTable_analisis.getColumnCount();
        String[] positions = {"1", "2", "3"};
        JComboBox combo = null;
        combo = new JComboBox<String>(positions);
        combo.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent ae) {

//                    JOptionPane.showMessageDialog(null, "" + );
            }
        });
        int e = 2;
        int i;
        for (i = e; i < 4; i++) {

            TableColumn column = jTable_analisis.getColumnModel().getColumn(i);
            column.setCellEditor(new DefaultCellEditor(combo));

        }

    }

    void obtener_result() {
//        int colum = jTable_analisis.getColumnCount();
        int fila = jTable_analisis.getRowCount();
        int i = 0;
        int val = 0;
        int val1 = 0;
        int result = 0;
        for (i = 0; i < fila; i++) {

            String valor = (String) jTable_analisis.getValueAt(i, 2);
            String valor1 = (String) jTable_analisis.getValueAt(i, 3);
            // Con esta condición solo ponemos comas hasta el penúltimo valor :)
            if ((String) jTable_analisis.getValueAt(i, 2) == null && (String) jTable_analisis.getValueAt(i, 3) == null) {
            } else {
                val = Integer.parseInt(valor);
                val1 = Integer.parseInt(valor1);
                result = val * val1;
                jTable_analisis.setValueAt(result, i, 4);

//                JOptionPane.showMessageDialog(null, result);
            }
        }

    }

    void llenartabla_analisis() {

        Object[] columnas = {"Activo", "Amenaza", "Probabilidad", "Impacto", "Riesgo"};
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);
        String datos[] = new String[2];
//        String datos1[] = new String[1];
        String sql_act_ame = " select nombre_activo, nombre_amenaza from activo_amenaza "
                + "inner join activo on activo_amenaza.activos_idactivos=activo.idactivo "
                + "inner join amenaza on activo_amenaza.amenazas_idamenaza=amenaza.idamenaza";
//        String sql_ame_nom = "select ame.nombre_amenaza from amenaza ame join activo_amenaza am on am.amenazas_idamenaza=ame.idamenaza"
//                + " where am.amenazas_idamenaza";
        try {
            Statement st = cxn.createStatement();
            ResultSet rs = st.executeQuery(sql_act_ame);

            while (rs.next()) {
                datos[0] = rs.getString("nombre_activo");
                datos[1] = rs.getString("nombre_amenaza");
                modelo.addRow(datos);

            }

            jTable_analisis.setModel(modelo);
            ancho_columnas();
        } catch (SQLException ex) {
            Logger.getLogger(RegistroUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        llenartabla_analisis();
        mostrar_combox();


    }//GEN-LAST:event_jButton6ActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        this.setVisible(false);
        Modulos modu = new Modulos();
        modu.setVisible(true);

    }//GEN-LAST:event_jLabel10MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        int fila = jTable_analisis.getRowCount();
        int i = 0;
        int id_cruce = 0;

        try {
            for (i = 0; i < fila; i++) {

                if ((String) jTable_analisis.getValueAt(i, 2) == null && (String) jTable_analisis.getValueAt(i, 3) == null) {

                } else {
                    String nom_amenaza = (String) jTable_analisis.getValueAt(i, 1);
                    String probabilidad = (String) jTable_analisis.getValueAt(i, 2);
                    String impacto = (String) jTable_analisis.getValueAt(i, 3);
                    int pro = Integer.parseInt(probabilidad);
                    int imp = Integer.parseInt(impacto);
                    int riesgo = (int) jTable_analisis.getValueAt(i, 4);

                    String sql = "select id_cruce from activo_amenaza inner join amenaza on "
                            + "activo_amenaza.amenazas_idamenaza=amenaza.idamenaza where nombre_amenaza='" + nom_amenaza + "'";
                    Statement st = cxn.createStatement();
                    ResultSet rs = st.executeQuery(sql);
                    while (rs.next()) {
                        id_cruce = rs.getInt("id_cruce");

                    }
                    String sql_insert = "insert into analisis (probabilidad, impacto, riesgo, activo_amenaza_id)values(?,?,?,?)";
                    PreparedStatement dato = cxn.prepareStatement(sql_insert);

                    dato.setInt(1, pro);
                    dato.setInt(2, imp);
                    dato.setInt(3, riesgo);
                    dato.setInt(4, id_cruce);
                    dato.executeUpdate();

                }

            }
            JOptionPane.showMessageDialog(null, "Se guardaron los datos de analisis");

        } catch (SQLException e) {
            System.err.println(e);
        }

    }//GEN-LAST:event_jButton9ActionPerformed
    public void ancho_columnas() {
        jTable_analisis.getColumnModel().getColumn(0).setPreferredWidth(180);
        jTable_analisis.getColumnModel().getColumn(1).setPreferredWidth(650);
        jTable_analisis.getColumnModel().getColumn(2).setPreferredWidth(140);
        jTable_analisis.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTable_analisis.getColumnModel().getColumn(4).setPreferredWidth(95);

    }
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        obtener_result();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nuevoActionPerformed
        llenartabla_analisis();
        mostrar_combox();
    }//GEN-LAST:event_jButton_nuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Analisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Analisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Analisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Analisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Analisis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    public static javax.swing.JButton jButton_nuevo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_analisis;
    // End of variables declaration//GEN-END:variables
}
