/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacion;

//import javafx.scene.paint.Color;
import javax.swing.JPanel;

/**
 *
 * @author barcelona
 */
public class Modulos extends javax.swing.JFrame {

    /**
     * Creates new form Modulos
     */
    public Modulos() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel_ingresos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel_home = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel_cruces = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel_analisis = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel_aplicacion = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel_reportes = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(233, 235, 238));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(45, 102, 169));

        jLabel13.setBackground(new java.awt.Color(42, 78, 184));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(137, 137, 137));
        jLabel13.setText("X");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(728, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 120));

        jPanel_ingresos.setBackground(new java.awt.Color(224, 226, 229));
        jPanel_ingresos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_ingresosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_ingresosMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Edit_Property_55px.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setText("Ingresos");

        javax.swing.GroupLayout jPanel_ingresosLayout = new javax.swing.GroupLayout(jPanel_ingresos);
        jPanel_ingresos.setLayout(jPanel_ingresosLayout);
        jPanel_ingresosLayout.setHorizontalGroup(
            jPanel_ingresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ingresosLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel_ingresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27))
        );
        jPanel_ingresosLayout.setVerticalGroup(
            jPanel_ingresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ingresosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(45, 45, 45))
        );

        jPanel2.add(jPanel_ingresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 130, 120));

        jPanel_home.setBackground(new java.awt.Color(224, 226, 229));
        jPanel_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_homeMouseExited(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Home_55px.png"))); // NOI18N
        jLabel5.setText("home");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 255));
        jLabel6.setText("Home");

        javax.swing.GroupLayout jPanel_homeLayout = new javax.swing.GroupLayout(jPanel_home);
        jPanel_home.setLayout(jPanel_homeLayout);
        jPanel_homeLayout.setHorizontalGroup(
            jPanel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_homeLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel_homeLayout.setVerticalGroup(
            jPanel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_homeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 130, 120));

        jPanel_cruces.setBackground(new java.awt.Color(224, 226, 229));
        jPanel_cruces.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_crucesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_crucesMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Data_Transfer_55px.png"))); // NOI18N
        jLabel3.setText("home");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 255));
        jLabel4.setText("Cruces");

        javax.swing.GroupLayout jPanel_crucesLayout = new javax.swing.GroupLayout(jPanel_cruces);
        jPanel_cruces.setLayout(jPanel_crucesLayout);
        jPanel_crucesLayout.setHorizontalGroup(
            jPanel_crucesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_crucesLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel_crucesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        jPanel_crucesLayout.setVerticalGroup(
            jPanel_crucesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_crucesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(45, 45, 45))
        );

        jPanel2.add(jPanel_cruces, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 130, 120));

        jPanel_analisis.setBackground(new java.awt.Color(224, 226, 229));
        jPanel_analisis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_analisisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_analisisMouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Search_55px_1.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 255));
        jLabel8.setText("Analisis");

        javax.swing.GroupLayout jPanel_analisisLayout = new javax.swing.GroupLayout(jPanel_analisis);
        jPanel_analisis.setLayout(jPanel_analisisLayout);
        jPanel_analisisLayout.setHorizontalGroup(
            jPanel_analisisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_analisisLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel_analisisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(31, 31, 31))
        );
        jPanel_analisisLayout.setVerticalGroup(
            jPanel_analisisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_analisisLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(45, 45, 45))
        );

        jPanel2.add(jPanel_analisis, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 130, 120));

        jPanel_aplicacion.setBackground(new java.awt.Color(224, 226, 229));
        jPanel_aplicacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_aplicacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_aplicacionMouseExited(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Checklist_55px_1.png"))); // NOI18N
        jLabel9.setText("home");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 255));
        jLabel10.setText(" Aplicaciòn");

        javax.swing.GroupLayout jPanel_aplicacionLayout = new javax.swing.GroupLayout(jPanel_aplicacion);
        jPanel_aplicacion.setLayout(jPanel_aplicacionLayout);
        jPanel_aplicacionLayout.setHorizontalGroup(
            jPanel_aplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_aplicacionLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel_aplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel_aplicacionLayout.setVerticalGroup(
            jPanel_aplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_aplicacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel_aplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 130, 120));

        jPanel_reportes.setBackground(new java.awt.Color(224, 226, 229));
        jPanel_reportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_reportesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_reportesMouseExited(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Resume_55px.png"))); // NOI18N
        jLabel11.setText("home");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 255));
        jLabel12.setText("Reportes");

        javax.swing.GroupLayout jPanel_reportesLayout = new javax.swing.GroupLayout(jPanel_reportes);
        jPanel_reportes.setLayout(jPanel_reportesLayout);
        jPanel_reportesLayout.setHorizontalGroup(
            jPanel_reportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_reportesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel_reportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel_reportesLayout.setVerticalGroup(
            jPanel_reportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_reportesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(45, 45, 45))
        );

        jPanel2.add(jPanel_reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 130, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_homeMouseEntered
        // TODO add your handling code here:
        setColor(jPanel_home);
    }//GEN-LAST:event_jPanel_homeMouseEntered

    private void jPanel_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_homeMouseExited
        // TODO add your handling code here:
        resetColor(jPanel_home);
    }//GEN-LAST:event_jPanel_homeMouseExited

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel13MousePressed

    private void jPanel_ingresosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_ingresosMouseEntered
        // TODO add your handling code here:
        setColor(jPanel_ingresos);
    }//GEN-LAST:event_jPanel_ingresosMouseEntered

    private void jPanel_ingresosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_ingresosMouseExited
        // TODO add your handling code here:
        resetColor(jPanel_ingresos);
    }//GEN-LAST:event_jPanel_ingresosMouseExited

    private void jPanel_crucesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_crucesMouseEntered
        // TODO add your handling code here:
        setColor(jPanel_cruces);
    }//GEN-LAST:event_jPanel_crucesMouseEntered

    private void jPanel_crucesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_crucesMouseExited
        // TODO add your handling code here:
        resetColor(jPanel_cruces);
    }//GEN-LAST:event_jPanel_crucesMouseExited

    private void jPanel_analisisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_analisisMouseEntered
        // TODO add your handling code here:
        setColor(jPanel_analisis);
    }//GEN-LAST:event_jPanel_analisisMouseEntered

    private void jPanel_analisisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_analisisMouseExited
        // TODO add your handling code here:
        resetColor(jPanel_analisis);
    }//GEN-LAST:event_jPanel_analisisMouseExited

    private void jPanel_aplicacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_aplicacionMouseEntered
        // TODO add your handling code here:
        setColor(jPanel_aplicacion);
    }//GEN-LAST:event_jPanel_aplicacionMouseEntered

    private void jPanel_aplicacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_aplicacionMouseExited
        // TODO add your handling code here:
        resetColor(jPanel_aplicacion);
    }//GEN-LAST:event_jPanel_aplicacionMouseExited

    private void jPanel_reportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_reportesMouseEntered
        // TODO add your handling code here:
        setColor(jPanel_reportes);
    }//GEN-LAST:event_jPanel_reportesMouseEntered

    private void jPanel_reportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_reportesMouseExited
        // TODO add your handling code here:
        resetColor(jPanel_reportes);
    }//GEN-LAST:event_jPanel_reportesMouseExited

    private void jPanel_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_homeMouseClicked
        // TODO add your handling code here:
        Administrador admin= new Administrador();
        admin.setVisible(true);
        Login lg= new Login();
        dispose();
          
     
      
    }//GEN-LAST:event_jPanel_homeMouseClicked
    public void setColor(JPanel jpanel){
        
        jpanel.setBackground(new java.awt.Color(204,203,203));
        
    }
    public void resetColor(JPanel jpanel){
        
        jpanel.setBackground(new java.awt.Color(224,226,229));
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modulos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_analisis;
    private javax.swing.JPanel jPanel_aplicacion;
    private javax.swing.JPanel jPanel_cruces;
    private javax.swing.JPanel jPanel_home;
    private javax.swing.JPanel jPanel_ingresos;
    private javax.swing.JPanel jPanel_reportes;
    // End of variables declaration//GEN-END:variables
}
